# Site wide configuration

title:            Thoughts
locale:           en_US
url:  http://vishnu667.github.io
#url:  http://127.0.0.1:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Vishnu Prasad
  avatar: vishnu.jpg
  bio: "Just another boring time Travelling programmer from the streets of Gotham."
  email: vishnu667@gmail.com
  disqus-shortname:
  twitter: vishnu667
  facebook: vishnu667
  google:
    plus: vishnu667
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: vishnu667
  stackoverflow: 2104970/vishnu667
  linkedin: vishnu667
  xing: #username
  instagram: vishnu667
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: vishnu667
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: vishnu667
  gitter: https://gitter.im/vishnu667/vishnu667.github.io
  codepen: #username

include: [".htaccess"]
exclude: ["vendor","lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
